[[redirects]]
  from = "/*"
  to = "/mfe-angular-app/index.html"
  status = 200
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://micro-frontend-service.netlify.app"
    Access-Control-Allow-Credentials = true
    Cust-head = "siva"